name: docker-releaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  docker-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.TAG }} .
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.TAG }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Push Docker image with version tag
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.TAG }}

      - name: Push Docker image with latest tag
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
