name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Login to Docker registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        if: success()
        run: |
            docker build -t ghcr.io/${{ github.repository }}:${{ github.ref/refs\/tags\// }} .
            docker push ghcr.io/${{ github.repository }}:${{ github.ref/refs\/tags\// }}
